<?php 
/**
 * ZF2 Buch Kapitel 11
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 11.9 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 11.9</h1>
<h3>Konfiguration für Navigation-Service</h3>
<pre>
&lt;?php
return array(
    'navigation' => array(
        'default' => array(
            'home' => array(
                'label'  => 'Startseite',
                'type'   => 'uri',
                'uri'    => '/',
            ),
            'pizzas' => array(
                'label'  => 'Pizzen',
                'type'   => 'uri',
                'pages'  => array(
                    'salami' => array(
                        'label'  => 'Pizza Salami',
                        'type'   => 'uri',
                        'uri'    => '/pizza/salami',
                        'pages'  => array(
                            'offer' => array(
                                'label'  => 'Monatsangebot',
                                'type'   => 'uri',
                                'uri'    => '/pizza/angebot',
                            ),
                        ),
                    ),
                    'melon' => array(
                        'label'  => 'Pizza Melone',
                        'type'   => 'uri',
                        'uri'    => '/pizza/melone',
                    ),
                ),
            ),
        ),
    ),
);
</pre>
</div>
</div>
