<?php 
/**
 * ZF2 Buch Kapitel 11
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 11.12 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 11.12</h1>
<h3>Ausgabe von Breadcrumbs mit <code>Navigation</code> View-Helper</h3>
<pre>
&lt;?php
use Zend\Navigation\Navigation;

$config = array(
    'pages' => array(
        'pizzas' => array(
            'label'  => 'Pizzen',
            'type'   => 'uri',
            'uri'    => '/pizza',
            'pages'  => array(
                'salami' => array(
                    'label'  => 'Pizza Salami',
                    'type'   => 'uri',
                    'uri'    => '/pizza/salami',
                    'pages'  => array(
                        'offer' => array(
                            'label'  => 'Monatsangebot',
                            'type'   => 'uri',
                            'uri'    => '/pizza/angebot',
                            'active' => true,
                        ),
                    ),
                ),
            ),
        ),
    ),
);

$navigation = new Navigation($config['pages']);

echo $this->navigation()->breadcrumbs()->render($navigation);
</pre>
<h3>Ausgabe</h3>
<pre>
<?php 
use Zend\Navigation\Navigation;

$config = array(
    'pages' => array(
        'pizzas' => array(
            'label'  => 'Pizzen',
            'type'   => 'uri',
            'uri'    => '/pizza',
            'pages'  => array(
                'salami' => array(
                    'label'  => 'Pizza Salami',
                    'type'   => 'uri',
                    'uri'    => '/pizza/salami',
                    'pages'  => array(
                        'offer' => array(
                            'label'  => 'Monatsangebot',
                            'type'   => 'uri',
                            'uri'    => '/pizza/angebot',
                            'active' => true,
                        ),
                    ),
                ),
            ),
        ),
    ),
);

$navigation = new Navigation($config['pages']);

echo(htmlspecialchars($this->navigation()->breadcrumbs()->render($navigation)));
?>
</pre>
</div>
</div>
