<?php 
/**
 * ZF2 Buch Kapitel 11
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 11.25 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 11.25</h1>
<h3>Ausgabe eines Barcodes mit <code>Zend\Barcode</code></h3>
<pre>
&lt;?php
use Zend\Barcode\Barcode;

ob_clean();

Barcode::render(
    'code39', 
    'image', 
    array('text' => 'LUIGIS PIZZA-SERVICE'), 
    array('imageType' => 'gif')
);

exit;
</pre>
<h3>Ausgabe</h3>
<?php 
use Zend\Barcode\Barcode;

ob_clean();

Barcode::render(
    'code39', 
    'image', 
    array('text' => 'LUIGIS PIZZA-SERVICE'), 
    array('imageType' => 'gif')
);

exit;
?>
</div>
</div>
