<?php 
/**
 * ZF2 Buch Kapitel 11
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 11.8 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 11.8</h1>
<h3><code>Zend\Navigation</code> mit Array-Daten konfigurieren</h3>
<pre>
&lt;?php
use Zend\Navigation\Navigation;

$config = array(
    'pages' => array(
        'home' => array(
            'label'  => 'Startseite',
            'type'   => 'uri',
            'uri'    => '/',
        ),
        'pizzas' => array(
            'label'  => 'Pizzen',
            'type'   => 'uri',
            'pages'  => array(
                'salami' => array(
                    'label'  => 'Pizza Salami',
                    'type'   => 'uri',
                    'uri'    => '/pizza/salami',
                    'pages'  => array(
                        'offer' => array(
                            'label'  => 'Monatsangebot',
                            'type'   => 'uri',
                            'uri'    => '/pizza/angebot',
                        ),
                    ),
                ),
                'melon' => array(
                    'label'  => 'Pizza Melone',
                    'type'   => 'uri',
                    'uri'    => '/pizza/melone',
                ),
            ),
        ),
    ),
);

$navigation = new Navigation($config['pages']);

echo $this->navigation()->menu($navigation);
</pre>
<h3>Ausgabe</h3>
<pre>
<?php 
use Zend\Navigation\Navigation;

$config = array(
    'pages' => array(
        'home' => array(
            'label'  => 'Startseite',
            'type'   => 'uri',
            'uri'    => '/',
        ),
        'pizzas' => array(
            'label'  => 'Pizzen',
            'type'   => 'uri',
            'pages'  => array(
                'salami' => array(
                    'label'  => 'Pizza Salami',
                    'type'   => 'uri',
                    'uri'    => '/pizza/salami',
                    'pages'  => array(
                        'offer' => array(
                            'label'  => 'Monatsangebot',
                            'type'   => 'uri',
                            'uri'    => '/pizza/angebot',
                        ),
                    ),
                ),
                'melon' => array(
                    'label'  => 'Pizza Melone',
                    'type'   => 'uri',
                    'uri'    => '/pizza/melone',
                ),
            ),
        ),
    ),
);

$navigation = new Navigation($config['pages']);

echo(htmlspecialchars($this->navigation()->menu($navigation)));
?>
</pre>
</div>
</div>
