<?php 
/**
 * ZF2 Buch Kapitel 11
 * 
 * Das Buch 'Zend Framework 2 - Das Praxisbuch'
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 11.5 view script
 * 
 * @package    Application
 */


?>
<div class='row'>
<div class='span9'>
<h1>Listing 11.5</h1>
<h3>Translator für <code>AbstractValidator</code> einrichten</h3>
<pre>
&lt;?php
use Zend\Debug\Debug;
use Zend\Mvc\I18n\Translator;
use Zend\Validator\AbstractValidator;
use Zend\Validator\EmailAddress;
use Zend\Validator\Hostname;
use Zend\Validator\Isbn;

$file = LUIGI_ROOT . '/module/Application/language/Zend_Validate.php';

$translate = new Translator();
$translate->addTranslationFile('phpArray', $file);

AbstractValidator::setDefaultTranslator($translate);

$value = '1-2345-6789-0';
$validator = new Isbn(array('separator' => '-'));
Debug::dump($validator->isValid($value));
Debug::dump($validator->getMessages());

$value = 'horst@das@gibt@es@nicht.biz';
$validator = new EmailAddress(array('allow' => Hostname::ALLOW_DNS));
Debug::dump($validator->isValid($value));
Debug::dump($validator->getMessages());
</pre>
<h3>Ausgabe</h3>
<?php 
use Zend\Debug\Debug;
use Zend\Mvc\I18n\Translator;
use Zend\Validator\AbstractValidator;
use Zend\Validator\EmailAddress;
use Zend\Validator\Hostname;
use Zend\Validator\Isbn;

$file = LUIGI_ROOT . '/module/Application/language/Zend_Validate.php';

$translate = new Translator();
$translate->addTranslationFile('phpArray', $file);

AbstractValidator::setDefaultTranslator($translate);

$value = '1-2345-6789-0';
$validator = new Isbn(array('separator' => '-'));
Debug::dump($validator->isValid($value));
Debug::dump($validator->getMessages());

$value = 'horst@das@gibt@es@nicht.biz';
$validator = new EmailAddress(array('allow' => Hostname::ALLOW_DNS));
Debug::dump($validator->isValid($value));
Debug::dump($validator->getMessages());
?>
</div>
</div>
