<?php 
/**
 * ZF2 Buch Kapitel 11
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Index view script
 * 
 * @package    Application
 */
?>
<h1>Listings - Kapitel 11</h1>
<table class="table table-bordered table-striped table-hover table-condensed">
<thead>
<tr>
<th>Listing</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="/listing/listing1101">Listing 11.1</a></td>
<td>Beispiel für den Einsatz von <code>Zend\I18n\Translator</code></td>
</tr>
<tr>
<td><a href="/listing/listing1102">Listing 11.2</a></td>
<td>Konfiguration für <code>Zend\I18n\Translator</code></td>
</tr>
<tr>
<td><a href="/listing/listing1103">Listing 11.3</a></td>
<td>Modul-Klasse für Konfiguration der <code>TranslatorServiceFactory</code></td>
</tr>
<tr>
<td><a href="/listing/listing1104">Listing 11.4</a></td>
<td>Einsatz der <code>Zend\I18n</code> View-Helper</td>
</tr>
<tr>
<td><a href="/listing/listing1105">Listing 11.5</a></td>
<td>Translator für <code>AbstractValidator</code> einrichten</td>
</tr>
<tr>
<td><a href="/listing/listing1106">Listing 11.6</a></td>
<td><code>Zend\Navigation</code> mit URI-Seiten erstellen</td>
</tr>
<tr>
<td><a href="/listing/listing1107">Listing 11.7</a></td>
<td><code>Zend\Navigation</code> mit MVC-Seiten und Router einrichten</td>
</tr>
<tr>
<td><a href="/listing/listing1108">Listing 11.8</a></td>
<td><code>Zend\Navigation</code> mit Array-Daten konfigurieren</td>
</tr>
<tr>
<td><a href="/listing/listing1109">Listing 11.9</a></td>
<td>Konfiguration für Navigation-Service</td>
</tr>
<tr>
<td><a href="/listing/listing1110">Listing 11.10</a></td>
<td>Modul-Klasse für Konfiguration der <code>DefaultNavigationFactory</code></td>
</tr>
<tr>
<td><a href="/listing/listing1111">Listing 11.11</a></td>
<td>Ausgabe eines Menüs mit <code>Navigation</code> View-Helper</td>
</tr>
<tr>
<td><a href="/listing/listing1112">Listing 11.12</a></td>
<td>Ausgabe von Breadcrumbs mit <code>Navigation</code> View-Helper</td>
</tr>
<tr>
<td><a href="/listing/listing1113">Listing 11.13</a></td>
<td><code>Zend\Navigation</code> mit <code>Zend\Acl</code> einschränken</td>
</tr>
<tr>
<td><a href="/listing/listing1114">Listing 11.14</a></td>
<td><code>Zend\Paginator</code> mit <code>Array</code> Adapter</td>
</tr>
<tr>
<td><a href="/listing/listing1115">Listing 11.15</a></td>
<td><code>Zend\Paginator</code> mit <code>DbSelect</code> Adapter</td>
</tr>
<tr>
<td><a href="/listing/listing1116">Listing 11.16</a></td>
<td>Konfigurationsdatei für das Modul <code>Pizza</code></td>
</tr>
<tr>
<td><a href="/listing/listing1117">Listing 11.17</a></td>
<td>Action-Controller, der ein <code>Paginator</code>-Objekt vorbereitet</td>
</tr>
<tr>
<td><a href="/listing/listing1118">Listing 11.18</a></td>
<td>View-Skript, das die <code>Paginator</code>-Daten und die Seitennavigation ausgibt</td>
</tr>
<tr>
<td><a href="/listing/listing1119">Listing 11.19</a></td>
<td>View-Skript für die Ausgabe der Seitennavigation</td>
</tr>
<tr>
<td><a href="/listing/listing1120">Listing 11.20</a></td>
<td>RSS Feed einlesen mit <code>Zend\Feed\Reader</code></td>
</tr>
<tr>
<td><a href="/listing/listing1121">Listing 11.21</a></td>
<td>RSS Feed erstellen mit <code>Zend\Feed\Writer</code></td>
</tr>
<tr>
<td><a href="/listing/listing1122">Listing 11.22</a></td>
<td>Modul-Klasse zum Aktivieren der View-Strategy für Feeds</td>
</tr>
<tr>
<td><a href="/listing/listing1123">Listing 11.23</a></td>
<td>Kodierung eines Arrays mit <code>Json::encode()</code></td>
</tr>
<tr>
<td><a href="/listing/listing1124">Listing 11.24</a></td>
<td>Ausgabe einer Tagwolke mit <code>Zend\Tag\Cloud</code></td>
</tr>
<tr>
<td><a href="/listing/listing1125">Listing 11.25</a></td>
<td>Ausgabe eines Barcodes mit <code>Zend\Barcode</code></td>
</tr>
</tbody>
</table>
